[package]
name = "dab"
version = "0.2.0"
edition = "2021"
authors = ["Sayan Nandan <nandansayan@outlook.com>"]
license = "Apache-2.0"
repository = "https://github.com/ohsayan/dab"
readme = "README.md"

[dependencies]
cargo_toml = "0.11.5"
